import { NextRequest, NextResponse } from "next/server"
import { safeLog } from "./lib/log-sanitizer"
import { auth } from "@/lib/auth-edge"

import { db } from "./lib/db"
import { Redis } from "@upstash/redis"

// Create Redis client if env vars exist
const redisUrl = process.env.UPSTASH_REDIS_REST_URL
const redisToken = process.env.UPSTASH_REDIS_REST_TOKEN
const redis = redisUrl && redisToken ? new Redis({ url: redisUrl, token: redisToken }) : null

const AUTH_PAGES = ["/login", "/register"]
const PORTAL_AUTH_PAGES = ["/portal/login"]
// Routes that bypass the session check. The SEO routes (sitemap.xml,
// robots.txt) are generated by Next.js from app/sitemap.ts and
// app/robots.ts and must be publicly crawlable for Google indexing.
const PUBLIC_PREFIXES = [
  "/clinica",
  "/portal/schedule",
  "/legal",
  "/forgot-password",
  "/reset-password",
  "/sitemap.xml",
  "/robots.txt",
  "/api/webhooks",
]

// ============================================================================
// Per-IP rate limit buckets (separate from per-email buckets in lib/auth.ts).
//
// Why two layers:
//   - Per-IP (here): blocks botnets spraying many emails from one host.
//   - Per-email (auth.ts): blocks single-account brute force across many IPs.
// Together they cover both credential stuffing and password spray attacks.
// ============================================================================

interface IpBucket {
  count: number
  resetAt: number
}

const globalIpBuckets = new Map<string, IpBucket>();

const IP_LIMITS: Record<string, { max: number; windowMs: number; failClosed: boolean }> = {
  // Auth endpoints — strict.
  "/api/auth/": { max: 30, windowMs: 60_000, failClosed: true },           // 30 / min per IP
  "/api/admin/seed-medications": { max: 2, windowMs: 3_600_000, failClosed: true }, // 2 / hour per IP
  // tRPC — generous for normal app use, blocks scraping.
  "/api/trpc/": { max: 600, windowMs: 600_000, failClosed: false },         // 600 / 10 min
  // Generic API.
  "/api/": { max: 300, windowMs: 60_000, failClosed: false },               // 300 / min per IP
}

async function checkIpRateLimit(
  ip: string,
  path: string,
): Promise<{ ok: boolean; retryAfter: number; bucket: string }> {
  // Find the most specific matching bucket.
  let matched: string | null = null
  for (const prefix of Object.keys(IP_LIMITS)) {
    if (path.startsWith(prefix)) {
      if (!matched || prefix.length > matched.length) matched = prefix
    }
  }
  if (!matched) return { ok: true, retryAfter: 0, bucket: "none" }

  const cfg = IP_LIMITS[matched]
  const key = `rl:ip:${ip}:${matched}`
  const now = Date.now()

  try {
    if (redis) {
      // UPSTASH REDIS IMPLEMENTATION (Distributed)
      const windowSec = Math.ceil(cfg.windowMs / 1000)
      
      const [[_countResult], [count]] = await redis.pipeline()
        .incr(key)
        .expire(key, windowSec, "NX")
        .exec() as any[]
      
      if (count > cfg.max) {
        const ttl = await redis.ttl(key)
        return { ok: false, retryAfter: Math.max(1, ttl), bucket: matched }
      }
      return { ok: true, retryAfter: 0, bucket: matched }
    } else {
      // IN-MEMORY FALLBACK (Ephemeral)
      const raw = globalIpBuckets.get(key)
      const bucket: IpBucket = raw ? raw : { count: 0, resetAt: now + cfg.windowMs }

      if (now >= bucket.resetAt) {
        bucket.count = 0
        bucket.resetAt = now + cfg.windowMs
      }

      bucket.count += 1

      if (bucket.count > cfg.max) {
        const retryAfter = Math.max(1, Math.ceil((bucket.resetAt - now) / 1000))
        globalIpBuckets.set(key, bucket)
        return { ok: false, retryAfter, bucket: matched }
      }

      globalIpBuckets.set(key, bucket)
      return { ok: true, retryAfter: 0, bucket: matched }
    }
  } catch (err) {
    safeLog("error", "proxy.ratelimit_failed", {
      ip: ip.slice(0, 8) + "***",
      path,
      bucket: matched,
      error: err instanceof Error ? err.message : "unknown",
    })
    return { ok: !cfg.failClosed, retryAfter: cfg.failClosed ? 60 : 0, bucket: matched }
  }
}

function getClientIp(req: NextRequest): string {
  // Cloud Run / Load Balancer sets x-forwarded-for; the leftmost is the original client.
  const xff = req.headers.get("x-forwarded-for")
  if (xff) {
    const hops = xff.split(",").map((s) => s.trim()).filter(Boolean)
    return hops[0] || "unknown"
  }
  const realIp = req.headers.get("x-real-ip")
  if (realIp) return realIp
  return "unknown"
}

export default async function proxy(req: NextRequest) {
  const { pathname } = req.nextUrl

  // ------------------------------------------------------------------
  // 0. HTTPS enforcement in production.
  //    Cloud Run Load Balancer terminates TLS. The x-forwarded-proto header carries
  //    the original scheme. If we see http://, redirect to https://
  //    (except in dev where this would loop).
  // ------------------------------------------------------------------
  if (process.env.NODE_ENV === "production") {
    const xfp = req.headers.get("x-forwarded-proto")
    const isHttps = xfp
      ? xfp.toLowerCase() === "https"
      : req.nextUrl.protocol === "https:"
    if (!isHttps && req.method === "GET") {
      const httpsUrl = new URL(req.url)
      httpsUrl.protocol = "https:"
      return NextResponse.redirect(httpsUrl, 308)
    }
  }

  // ------------------------------------------------------------------
  // 1. Per-IP rate limit for API paths and sensitive auth pages.
  // ------------------------------------------------------------------
  if (pathname.startsWith("/api/")) {
    const ip = getClientIp(req)
    const rl = await checkIpRateLimit(ip, pathname)
    if (!rl.ok) {
      safeLog("warn", "proxy.rate_limit_exceeded", {
        ip: ip.slice(0, 8) + "***",
        path: pathname,
        bucket: rl.bucket,
        retryAfter: rl.retryAfter,
      })
      return new NextResponse(
        JSON.stringify({
          error: "Demasiadas solicitudes. Intente de nuevo más tarde.",
        }),
        {
          status: 429,
          headers: {
            "Content-Type": "application/json",
            "Retry-After": String(rl.retryAfter),
            "X-RateLimit-Limit": rl.bucket,
            "X-RateLimit-Remaining": "0",
          },
        },
      )
    }
  }

  // ------------------------------------------------------------------
  // 2. Read the session EARLY so role-based redirects can run on EVERY
  //    page route (including `/`). We previously skipped this for public
  //    routes, which let a logged-in PATIENT browse `/doctor` and see the
  //    doctor dashboard with empty data (authz leak: 2026-07-07).
  //
  //    auth() decodes + verifies the JWT — a forged cookie returns null.
  //    Edge-safe via lib/auth-edge.ts (no Prisma/bcrypt/Redis imports).
  // ------------------------------------------------------------------
  let isLoggedIn = false
  let isPatient = false
  let sessionUser: any = null
  try {
    const session = await auth()
    isLoggedIn = !!session?.user
    isPatient = session?.user?.role === "PATIENT"
    sessionUser = session?.user
  } catch {
    isLoggedIn = false
    isPatient = false
  }

  // ------------------------------------------------------------------
  // IP Restriction for Staff (SECRETARY, ASSISTANT, NURSE)
  // ------------------------------------------------------------------
  if (isLoggedIn && sessionUser && ["SECRETARY", "ASSISTANT", "NURSE"].includes(sessionUser.role)) {
    const wsId = sessionUser.workspaceId
    if (wsId) {
      try {
        const ws = await db.workspace.findUnique({
          where: { id: wsId },
          select: { allowedIps: true },
        })
        if (ws?.allowedIps) {
          const clientIp = getClientIp(req)
          const allowedList = ws.allowedIps.split(",").map((ip: string) => ip.trim()).filter(Boolean)
          const isAllowed = allowedList.includes(clientIp) ||
            (process.env.NODE_ENV !== "production" && ["127.0.0.1", "::1", "localhost", "unknown"].includes(clientIp))

          if (!isAllowed) {
            safeLog("warn", "security.ip_restricted_access_attempt", {
              email: sessionUser.email,
              role: sessionUser.role,
              clientIp,
              allowedIps: ws.allowedIps,
            })
            if (pathname.startsWith("/api/")) {
              return new NextResponse(
                JSON.stringify({ error: "Acceso no permitido desde esta dirección IP." }),
                { status: 403, headers: { "Content-Type": "application/json" } }
              )
            }
            return NextResponse.redirect(new URL("/login?error=IP_RESTRICTED", req.url))
          }
        }
      } catch (err) {
        safeLog("error", "security.ip_check_failed", {
          email: sessionUser.email,
          error: err instanceof Error ? err.message : "unknown",
        })
      }
    }
  }

  // ------------------------------------------------------------------
  // 3. Public SEO routes + /portal/schedule (public booking page) — no
  //    auth check needed.
  // ------------------------------------------------------------------
  if (PUBLIC_PREFIXES.some((p) => pathname.startsWith(p))) {
    return NextResponse.next()
  }

  // /api/trpc/* handles its own per-procedure authz (publicProcedure vs
  // protectedProcedure in server/trpc.ts). Bypass the session check here so
  // that explicitly-public procedures (e.g. auth.requestEmailOtp,
  // auth.verifyEmailOtp, auth.requestPasswordReset) are reachable without
  // a session. Per-IP rate limiting (section 1) still applies.
  if (pathname.startsWith("/api/trpc/")) {
    return NextResponse.next()
  }

  // NextAuth.js v5 handles its own auth flow at /api/auth/* (csrf,
  // callback/credentials, session, signout). These endpoints must be
  // reachable WITHOUT a pre-existing session — the entire point of the
  // /api/auth/csrf endpoint is to bootstrap a login. Bypass the session
  // check (per-IP rate limiting above still applies).
  if (pathname.startsWith("/api/auth/")) {
    return NextResponse.next()
  }

  const isPortalPath = pathname.startsWith("/portal")
  const isPortalAuthPage = PORTAL_AUTH_PAGES.some((p) => pathname.startsWith(p))
  const isAuthPage = AUTH_PAGES.some((p) => pathname.startsWith(p))

  // ------------------------------------------------------------------
  // 4. Root `/` — send authenticated users to their role-appropriate
  //    dashboard. Unauthenticated users see the marketing landing.
  //    Before this change a patient who closed + reopened the browser
  //    would land on `/` and the page rendered the marketing landing
  //    regardless of session — leaving them stranded on a page with no
  //    portal entry point (auth.portal_login_ok in logs, but UX broken).
  // ------------------------------------------------------------------
  if (pathname === "/") {
    if (isLoggedIn) {
      const target = isPatient ? "/portal" : "/doctor"
      return NextResponse.redirect(new URL(target, req.url))
    }
    return NextResponse.next()
  }

  // ------------------------------------------------------------------
  // 5. Role isolation (2026-07-07): a PATIENT session must only see
  //    `/portal/*`. A doctor/staff/admin session must NOT see `/portal/*`
  //    except the login page. Without this, a patient navigating back to
  //    `/doctor` rendered the doctor dashboard with empty data, and
  //    inversely a doctor could navigate into the patient portal.
  // ------------------------------------------------------------------
  if (isLoggedIn && isPatient && !isPortalPath && !pathname.startsWith("/api/")) {
    return NextResponse.redirect(new URL("/portal", req.url))
  }
  if (isLoggedIn && !isPatient && isPortalPath && !isPortalAuthPage) {
    return NextResponse.redirect(new URL("/", req.url))
  }

  // ------------------------------------------------------------------
  // 6. Auth pages when already logged in — send to the role-appropriate
  //    landing so the user doesn't see a "login" form while authenticated.
  // ------------------------------------------------------------------
  if (isLoggedIn && isAuthPage) {
    const target = isPatient ? "/portal" : "/doctor"
    return NextResponse.redirect(new URL(target, req.url))
  }
  if (isLoggedIn && isPortalAuthPage && isPatient) {
    return NextResponse.redirect(new URL("/portal", req.url))
  }

  // ------------------------------------------------------------------
  // 7. Not logged in — send to the correct login page based on intent.
  // ------------------------------------------------------------------
  if (!isLoggedIn) {
    if (isPortalAuthPage || isAuthPage) return NextResponse.next()
    if (isPortalPath) {
      return NextResponse.redirect(new URL("/portal/login", req.url))
    }
    return NextResponse.redirect(new URL("/login", req.url))
  }

  return NextResponse.next()
}

export const config = {
  // Match everything except static assets and uploads. Includes /api/* so
  // we can apply per-IP rate limits before requests hit handlers.
  matcher: ["/((?!_next/static|_next/image|favicon.ico|icon|apple-icon|logo-|uploads).*)"],
  // Next.js 16 proxy always runs on Node.js runtime — no need to specify.
  // See: https://nextjs.org/docs/messages/middleware-to-proxy
}
