import { GoogleGenAI } from "@google/genai";

export async function generateContentForImage(imageBuffer: Buffer, apiKey: string, moduleDescription: string): Promise<{caption: string, hashtags: string}> {
  console.log("Sending image to Google AI Studio (Gemini 3 Preview)...");
  
  const ai = new GoogleGenAI({ apiKey });

  const prompt = `Eres un Community Manager experto en SaaS médico en Venezuela. 
Analiza esta captura de pantalla de nuestro sistema MedSysVE y crea un texto atractivo para Instagram destacando las funcionalidades visibles.

Contexto sobre la imagen mostrada:
"${moduleDescription}"

Retorna un JSON estructurado de esta manera:
{
  "caption": "Tu texto aquí, atractivo y persuasivo, usa emojis y haz un Call-to-Action.",
  "hashtags": "#medsysve #saas #medicosvenezolanos #historiaclinica"
}`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: [
        prompt,
        {
          inlineData: {
            data: imageBuffer.toString("base64"),
            mimeType: "image/png"
          }
        }
      ],
      config: {
        responseMimeType: "application/json"
      }
    });

    const textResponse = response.text || "{}";
    const result = JSON.parse(textResponse);
    return {
      caption: result.caption || "¡Descubre la nueva función de MedSysVE!",
      hashtags: result.hashtags || "#medsysve"
    };
  } catch (error) {
    console.error("Error calling Google AI Studio:", error);
    throw error;
  }
}

export async function generateAIImage(prompt: string, project: string, location: string): Promise<Buffer> {
  console.log("Generating image with Vertex AI (Imagen 3) via REST API...");
  try {
    const { GoogleAuth } = require('google-auth-library');
    const axios = require('axios');
    const auth = new GoogleAuth({ scopes: 'https://www.googleapis.com/auth/cloud-platform' });
    const client = await auth.getClient();
    const token = await client.getAccessToken();

    const url = `https://${location}-aiplatform.googleapis.com/v1/projects/${project}/locations/${location}/publishers/google/models/imagegeneration@006:predict`;
    
    const response = await axios.post(url, {
      instances: [{ prompt }],
      parameters: {
        sampleCount: 1,
        aspectRatio: "1:1",
        outputOptions: { mimeType: "image/png" }
      }
    }, {
      headers: {
        'Authorization': `Bearer ${token.token}`,
        'Content-Type': 'application/json'
      }
    });

    const predictions = response.data.predictions;
    if (!predictions || predictions.length === 0) {
      throw new Error("No image generated by Vertex AI REST API");
    }

    const base64Str = predictions[0].bytesBase64;
    if (!base64Str) throw new Error("Image bytesBase64 are undefined");
    
    return Buffer.from(base64Str, 'base64');
  } catch (error: any) {
    console.error("Error generating AI Image:", error.response?.data || error.message);
    throw error;
  }
}
