import type { MetadataRoute } from "next"

/**
 * Dynamic robots.txt for MedSysVE.
 *
 * - Allow public marketing/auth/legal routes.
 * - Disallow authenticated areas (dashboard, portal, API, clinic admin,
 *   uploads, AI endpoints) so PHI and internal routes don't leak via
 *   search engine caches.
 * - Reference the dynamic sitemap at /sitemap.xml (also generated by
 *   Next.js from app/sitemap.ts).
 *
 * Last updated: 2026-07-06 (SEO F2).
 */
export default function robots(): MetadataRoute.Robots {
  const base = process.env.NEXT_PUBLIC_APP_URL ?? "https://www.medsysve.com"
  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/", "/register", "/login", "/forgot-password", "/legal/"],
        disallow: [
          "/api/",
          "/admin/",
          "/dashboard/",
          "/clinica/",
          "/doctor/",
          "/portal/",
          "/portal/login",
          "/uploads/",
          "/_next/",
        ],
      },
      {
        // AI crawlers: respect LOPDP Art. 19 (technical safeguards). We
        // don't authorize third-party AI training on the marketing site.
        userAgent: [
          "GPTBot",
          "CCBot",
          "anthropic-ai",
          "ClaudeBot",
          "Google-Extended",
        ],
        disallow: "/",
      },
    ],
    sitemap: `${base}/sitemap.xml`,
    host: base,
  }
}