export const ESPECIALIDADES_VE = [
  "Medicina General",
  "Medicina Interna",
  "Pediatría y Puericultura",
  "Ginecología y Obstetricia",
  "Cardiología",
  "Traumatología y Ortopedia",
  "Cirugía General",
  "Dermatología",
  "Neurología",
  "Neumonología",
  "Gastroenterología",
  "Urología",
  "Otorrinolaringología",
  "Oftalmología",
  "Oncología Médica",
  "Anestesiología",
  "Endocrinología",
  "Psiquiatría y Salud Mental",
  "Infectología",
  "Reumatología",
  "Nefrología",
  "Medicina de Emergencia y Urgencias",
  "Geriatría",
  "Medicina Familiar",
  "Cirugía Plástica y Reconstructiva",
  "Hematología",
  "Alergología e Inmunología",
  "Medicina Física y Rehabilitación (Fisiatría)",
  "Medicina Ocupacional",
  "Nutrición y Dietética",
  "Neonatología",
  "Cirugía Cardiovascular",
  "Cirugía Torácica",
  "Cirugía Pediátrica",
  "Radiología",
  "Patología",
  "Medicina Nuclear",
  "Genética Médica",
  "Toxicología",
] as const
