export const ESPECIALIDADES_VE = [
  "Medicina General",
  "Cardiología",
  "Gastroenterología",
  "Traumatología",
  "Pediatría",
  "Ginecología y Obstetricia",
  "Neurología",
  "Dermatología",
  "Oftalmología",
  "Otorrinolaringología",
  "Urología",
  "Neumología",
  "Endocrinología",
  "Nefrología",
  "Oncología",
  "Psiquiatría",
  "Cirugía General",
  "Cirugía Plástica",
  "Ortopedia",
  "Anestesiología",
  "Radiología",
  "Patología",
  "Medicina Interna",
  "Geriatría",
  "Reumatología",
  "Infectología",
  "Medicina de Emergencia",
  "Hematología",
  "Inmunología",
  "Medicina Ocupacional",
  "Nutrición y Dietética",
  "Fisiatría",
  "Medicina Familiar",
  "Neonatología",
  "Cirugía Cardiovascular",
  "Cirugía Torácica",
  "Cirugía Pediátrica",
  "Medicina Nuclear",
  "Genética Médica",
  "Toxicología",
]
